sudo: required
language: bash
env:
  global:
  - GH_REPO="github.com/${USER}/${SRC_REPO}.git"

before_install:

  - sudo apt-get -y update
  - sudo apt-get install -y git
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y acl
  - gem install asciidoctor

script:

 - git clone https://github.com/hemanth22/${SRC_REPO}.git
 - pwd
 - echo "Change to repository directory"
 - cd ${SRC_REPO}
 - echo "Checkout to branch repository"
 - git checkout ${BRANCH_NAME}
 - echo "Clean repository"
 - rm -rf ${SRC_REPO}/*
 - echo "Listing Output after above script"
 - echo "<br/>This repository is clean using Travis CI application." >> README.md
 - git remote
 - git config user.email ${EMAIL}
 - git config user.name ${USER}
 - git rm -r .
 - git commit -m "Clean repository from Travis build  $TRAVIS_BUILD_NUMBER"
 - git push "https://${GITHUB_API_KEY}@${SRC_REPO}" ${BRANCH_NAME}
#- git push "https://${GITHUB_API_KEY}@${GH_REPO}" ${BRANCH_NAME}

after_success:

 - ls -la

notifications:
  slack:
     rooms:
        - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
